// Hardware configuration of the ESP32 I2C master port. Defaults follow esp32c3_test/esp32_i2c_test/esp_i2c_master.

#ifndef I2CMASTERPORTESP32CFG_H
#define I2CMASTERPORTESP32CFG_H

#include "driver/i2c_master.h"

#ifndef BICO_PROTOCOL_BRIDGE_I2C_MASTER_PORT
#define BICO_PROTOCOL_BRIDGE_I2C_MASTER_PORT            I2C_NUM_0
#endif

#ifndef BICO_PROTOCOL_BRIDGE_I2C_MASTER_SDA_PIN
#define BICO_PROTOCOL_BRIDGE_I2C_MASTER_SDA_PIN         8
#endif

#ifndef BICO_PROTOCOL_BRIDGE_I2C_MASTER_SCL_PIN
#define BICO_PROTOCOL_BRIDGE_I2C_MASTER_SCL_PIN         9
#endif

#ifndef BICO_PROTOCOL_BRIDGE_I2C_MASTER_GLITCH_IGNORE_CNT
#define BICO_PROTOCOL_BRIDGE_I2C_MASTER_GLITCH_IGNORE_CNT   7
#endif

#ifndef BICO_PROTOCOL_BRIDGE_I2C_MASTER_INTERNAL_PULLUP
#define BICO_PROTOCOL_BRIDGE_I2C_MASTER_INTERNAL_PULLUP true
#endif

// Clock stretching timeout of a slave in microseconds.
#ifndef BICO_PROTOCOL_BRIDGE_I2C_MASTER_SCL_WAIT_US
#define BICO_PROTOCOL_BRIDGE_I2C_MASTER_SCL_WAIT_US     100000
#endif

// Clock frequency and slave address used by the reference test.
#ifndef BICO_PROTOCOL_BRIDGE_I2C_MASTER_DEFAULT_FREQ_HZ
#define BICO_PROTOCOL_BRIDGE_I2C_MASTER_DEFAULT_FREQ_HZ 400000
#endif

#ifndef BICO_PROTOCOL_BRIDGE_I2C_MASTER_DEFAULT_SLAVE_ADDRESS
#define BICO_PROTOCOL_BRIDGE_I2C_MASTER_DEFAULT_SLAVE_ADDRESS   0x6D
#endif

#endif /* I2CMASTERPORTESP32CFG_H */
