// Hardware configuration of the ESP32 I2C slave port. Defaults follow esp32c3_test/esp32_i2c_test/esp_i2c_slave.

#ifndef I2CSLAVEPORTESP32CFG_H
#define I2CSLAVEPORTESP32CFG_H

#include "driver/i2c_slave.h"

#ifndef BICO_PROTOCOL_BRIDGE_I2C_SLAVE_PORT
#define BICO_PROTOCOL_BRIDGE_I2C_SLAVE_PORT             I2C_NUM_0
#endif

#ifndef BICO_PROTOCOL_BRIDGE_I2C_SLAVE_SDA_PIN
#define BICO_PROTOCOL_BRIDGE_I2C_SLAVE_SDA_PIN          8
#endif

#ifndef BICO_PROTOCOL_BRIDGE_I2C_SLAVE_SCL_PIN
#define BICO_PROTOCOL_BRIDGE_I2C_SLAVE_SCL_PIN          9
#endif

// Address used by the reference test.
#ifndef BICO_PROTOCOL_BRIDGE_I2C_SLAVE_DEFAULT_ADDRESS
#define BICO_PROTOCOL_BRIDGE_I2C_SLAVE_DEFAULT_ADDRESS  0x6D
#endif

// Depth of the driver buffers; must not be smaller than the largest transfer of the driver (256 bytes).
#ifndef BICO_PROTOCOL_BRIDGE_I2C_SLAVE_TX_BUFFER_DEPTH
#define BICO_PROTOCOL_BRIDGE_I2C_SLAVE_TX_BUFFER_DEPTH  256
#endif

#ifndef BICO_PROTOCOL_BRIDGE_I2C_SLAVE_RX_BUFFER_DEPTH
#define BICO_PROTOCOL_BRIDGE_I2C_SLAVE_RX_BUFFER_DEPTH  256
#endif

#ifndef BICO_PROTOCOL_BRIDGE_I2C_SLAVE_INTERNAL_PULLUP
#define BICO_PROTOCOL_BRIDGE_I2C_SLAVE_INTERNAL_PULLUP  GPIO_PULLUP_ENABLE
#endif

#ifndef BICO_PROTOCOL_BRIDGE_I2C_SLAVE_TASK_STACK_SIZE
#define BICO_PROTOCOL_BRIDGE_I2C_SLAVE_TASK_STACK_SIZE  3072
#endif

#ifndef BICO_PROTOCOL_BRIDGE_I2C_SLAVE_TASK_PRIORITY
#define BICO_PROTOCOL_BRIDGE_I2C_SLAVE_TASK_PRIORITY    5
#endif

#endif /* I2CSLAVEPORTESP32CFG_H */
