# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  apt_packages:
    - default-jre
    - graphviz
    - wget
  jobs:
    build:
      html:
        - python -m pip install -r .readthedocsVenvRequirements.txt
        - wget -O /tmp/plantuml.jar https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar
        - ln -s /tmp/plantuml.jar /usr/bin/plantuml.jar
        - python -m sphinx -b html -c 5_buildEnviroment/docGen . $READTHEDOCS_OUTPUT/html
        - cp .readthedocsRootPage.html $READTHEDOCS_OUTPUT/html/index.html