# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

python:
   install:
   - requirements: .readthedocsVenvRequirements.txt

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  apt_packages:
    - default-jre
    - graphviz
  jobs:
    build:
      html:
        - sphinx-build -b html -c 5_buildEnviroment/docGen . $READTHEDOCS_OUTPUT/html