@startuml
title Configuration Service - Information Flow

package "System Startup Flow" {
    component "Central App Controller" as CAC1
    component "Config Service" as CS1
    component "NVM Driver" as NVM1

    CAC1 -down-> CS1 : ConfigService_Init()
    CS1 -down-> NVM1 : NVM_Read(config_addr)
    NVM1 -up-> CS1 : JSON config data
    CS1 -down-> CS1 : Parse JSON / Validate
    CS1 -up-> CAC1 : CONFIG_LOADED / DEFAULT_CONFIG_LOADED
}

package "SID 0x22 Read (Get) Flow" {
    component "Central App Controller" as CAC2
    component "Config Service" as CS2

    CAC2 -down-> CS2 : ConfigService_Get(did=0x1001)
    CS2 -down-> CS2 : Lookup DID in registry
    CS2 -down-> CS2 : Read config parameter
    CS2 -up-> CAC2 : data=[0x04, 0x00]
}

package "SID 0x2E Write (Validate + Set) Flow" {
    component "Central App Controller" as CAC3
    component "Config Service" as CS3
    component "NVM Driver" as NVM3

    CAC3 -down-> CS3 : ConfigService_Validate(did=0x1001, data=[0x08,0x00])
    CS3 -down-> CS3 : Lookup DID / Check range
    CS3 -up-> CAC3 : VALID / INVALID (nrc)
    CAC3 -down-> CS3 : ConfigService_Set(did=0x1001, data=[0x08,0x00])
    CS3 -down-> CS3 : Update internal config
    CS3 -down-> NVM3 : NVM_Write(JSON config)
    NVM3 -up-> CS3 : SUCCESS
    CS3 -up-> CAC3 : OK
}

@enduml