#ifndef CALIBRATION_SERVICEUNIT_H
#define CALIBRATION_SERVICEUNIT_H
#include <stdint.h>
#include "calibrationServiceCfg.h"
typedef enum CalibrationService_Status_t CalibrationService_Status_t;
typedef struct CalibrationService_CalibrationPoint_t CalibrationService_CalibrationPoint_t;
typedef struct CalibrationService_CalibrationData_t CalibrationService_CalibrationData_t;
CalibrationService_Status_t CalibrationServiceUnit_Init(void);
CalibrationService_Status_t CalibrationServiceUnit_DeInit(void);
CalibrationService_Status_t CalibrationServiceUnit_AddCalibrationPoint(uint8_t channelId, const CalibrationService_CalibrationPoint_t *pPoint);
CalibrationService_Status_t CalibrationServiceUnit_ClearCalibrationPoints(uint8_t channelId);
CalibrationService_Status_t CalibrationServiceUnit_ApplyCalibration(uint8_t channelId, float rawValue, float *pCalibratedValue);
CalibrationService_Status_t CalibrationServiceUnit_GetCalibrationData(uint8_t channelId, CalibrationService_CalibrationData_t *pData);
CalibrationService_Status_t CalibrationServiceUnit_SaveCalibration(uint8_t channelId);
CalibrationService_Status_t CalibrationServiceUnit_LoadCalibration(uint8_t channelId);
#endif
