# Add subdirectories

add_subdirectory(../3_swComp/layer1Driver/adcDriver/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/adcDriver)
add_subdirectory(../3_swComp/layer1Driver/gpioDriver/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/gpioDriver)
add_subdirectory(../3_swComp/layer1Driver/i2cMasterDriver/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/i2cMasterDriver)
add_subdirectory(../3_swComp/layer1Driver/i2cSlaveDriver/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/i2cSlaveDriver)
add_subdirectory(../3_swComp/layer1Driver/nvmDriver/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/nvmDriver)
add_subdirectory(../3_swComp/layer1Driver/pwmDriver/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/pwmDriver)
add_subdirectory(../3_swComp/layer1Driver/serialDriver/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/serialDriver)
add_subdirectory(../3_swComp/layer1Driver/spiMasterDriver/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/spiMasterDriver)
add_subdirectory(../3_swComp/layer1Driver/spiSlaveDriver/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/spiSlaveDriver)
add_subdirectory(../3_swComp/layer2Service/configService/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/configService)
add_subdirectory(../3_swComp/layer2Service/deserialize/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/deserialize)
add_subdirectory(../3_swComp/layer2Service/nvmService/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/nvmService)
add_subdirectory(../3_swComp/layer2Service/serialize/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/serialize)
add_subdirectory(../3_swComp/layer3Application/centralAppController/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/centralAppController)
add_subdirectory(../3_swComp/layer3Application/ANALOGAPP/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/ANALOGAPP)
add_subdirectory(../3_swComp/layer3Application/DIGITALAPP/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/DIGITALAPP)
add_subdirectory(../3_swComp/layer3Application/I2CAPP/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/I2CAPP)
add_subdirectory(../3_swComp/layer3Application/SPIAPP/6_test/gtest ${CMAKE_CURRENT_BINARY_DIR}/SPIAPP)