#ifndef SERIALDRIVERCFG_H
#define SERIALDRIVERCFG_H

#define SERIAL_CFG_DEFAULT_BAUDRATE     115200
#define SERIAL_CFG_DEFAULT_PARITY       0
#define SERIAL_CFG_DEFAULT_STOPBITS     1
#define SERIAL_CFG_DEFAULT_DATABITS     8
#define SERIAL_CFG_TIMEOUT_MS           1000
#define SERIAL_CFG_MAX_BUFFER_SIZE      256

#endif /* SERIALDRIVERCFG_H */
